language: objective-c
osx_image: xcode7

script:
    - cd GlossExample
    - sudo gem install cocoapods
    - pod install
    - xcodebuild clean build test -workspace GlossExample.xcworkspace -scheme GlossExample CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
